# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92066d17ed34de5cff4a5aeeb90ef16e1dd1c32bc86210713a5eb0acd9b2cc8a5787bc42aafbef1ebb4ae2b460472bd826599ae145662803fc54cdea0ae72f79

test:
  secret_key_base: a3cf6144bfb3ab5ff6c2e0f818aabb4143de9cb1d4c12976e807a2ca1b2025c10961fd2328224e404d4b7f34987ba81d6fa6d25565cba6c65d3fa624bd72c61a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
